# Generated by Django 4.0.3 on 2023-03-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='vin',
            new_name='automobile',
        ),
    ]
