# Generated by Django 4.0.3 on 2023-03-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_serviceappointment_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
