# Generated by Django 4.0.3 on 2023-03-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_serviceappointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
