# Generated by Django 4.0.3 on 2023-03-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_serviceappointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
