# Generated by Django 4.0.3 on 2023-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
