# Generated by Django 4.0.3 on 2023-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_remove_automobilevo_color_remove_automobilevo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='vip',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
